export enum InputKeys {
    ArrowUp = 'ArrowUp',
    ArrowDown = 'ArrowDown',
    ArrowLeft = 'ArrowLeft',
    ArrowRight = 'ArrowRight',
    Space = 'Space',
    Enter = 'Enter',
    Pause = 'Pause',
    ShiftLeft = 'ShiftLeft',
    ShiftRight = 'ShiftRight',
    ControlLeft = 'ControlLeft',
    Backspace = 'Backspace',
    AltLeft = 'AltLeft',
    W = 'KeyW', 
    A = 'KeyA', 
    S = 'KeyS', 
    D = 'KeyD', 
    C = 'KeyC', 
    Z = 'KeyZ', 
    Q = 'KeyQ', 
    E = 'KeyE',
    R = 'KeyR',
    P = 'KeyP',
    T = 'KeyT',
    I = 'KeyI',
    B = 'KeyB',
}